---
- name: Just the facts maam
  hosts: test-sw01
  remote_user: admin
#  ansible_port: 830
  connection: netconf
  tasks:
  - name: Juniper connection test
    wait_for: host={{ inventory_hostname }} port=830

  - name: Retrieve the facts
    junos_facts:  host={{ inventory_hostname }}
    register: ansible_facts

  - name: Print info
    debug: msg="{{ ansible_facts }}"
