---
- name: CONFIGURE CAMERA PORT DESCRIPTIONS
  hosts: junos_ex_camera
  tasks:
    - name: DEFINE PROVIDER
      set_fact:
        netconf:
          host: "{{ ansible_ssh_host }}"
          username: "{{ ansible_ssh_user }}"
          password: "{{ ansible_ssh_pass }}"
          port: "{{ port }}"
          transport: netconf
          timeout: 30

    - name: Juniper connection test
      wait_for: host={{ inventory_hostname }} port={{ port }}


    - name: Assign Security Camera Ports Description
      junos_config:
        lines:
          - set interfaces interface-range CAMERA-PORTS description security-camera-port
        comment: Set Camera-Port description
        provider: "{{ netconf }}"
