---
- name: CONFIGURE SYSTEM SETTINGS
  hosts: junos_mx
  tasks:
    - name: DEFINE PROVIDER
      set_fact:
        netconf:
          host: "{{ ansible_ssh_host }}"
          username: "{{ ansible_ssh_user }}"
          password: "{{ ansible_ssh_pass }}"
          port: "{{ port }}"
          transport: netconf
          timeout: 30
    - name: Juniper connection test
      wait_for: host={{ inventory_hostname }} port={{ port }}

    - name: Syslog settings
      junos_config:
        lines:
          - set system syslog user * any emergency
          - set system syslog host {{ syslog1 }} any info
          - set system syslog host {{ syslog2 }} any info
          - set system syslog file messages any notice
          - set system syslog file messages authorization info
          - deactivate system syslog file messages
          - set system syslog file interactive-commands interactive-commands any
          - set system syslog file User-Auth authorization any
          - set system syslog file User-Auth interactive-commands any
        comment: Update syslog settings
        provider: "{{ netconf }}"

    - name: Change Banner Message
      junos_banner:
        banner: login
        text: |
            +-------------------------------------------------------------+
            |               !!! Authorised access only !!!                |
            |     You are authorised to use this System for approved      |
            |     business purposes only. Use for any other purpose       |
            |     is prohibited.                                          |
            |                                                             |
            |     All transactional records generated by using this       |
            |       System are the property of ABC and may be             |
            |        used by ABC for any purpose. Authorised              |
            |     and unauthorised activities will be monitored.          |
            +-------------------------------------------------------------+

            +-------------------------------------------------------------+
            |     Disconnect IMMEDIATELY if you are not authorised        |
            |     For access to this system contact:                      |
            |                                                             |
            |                  person@example.com                         |
            +-------------------------------------------------------------+
        provider: "{{ netconf }}"
