# Uncomment for creation
- name: Create Vlans
  eos_vlan: name={{ item.name }} vlanid={{ item.vlanid }} state={{ item.state }}
    username={{ eapi_username }}
    password={{ eapi_password }}
    host={{ eapi_hostname }}
    port={{ eapi_port }}
    transport=https
  with_items: vlans
