---
- name: Get NXOS Facts
  gather_facts: false
  hosts: nxos_sw
  tasks:
    - name: Get Interface facts for devices
      nxos_facts:
        provider: "{{ nxapi }}"
        gather_subset: all
      register: nxosfacts_out
      when: ansible_network_os == 'nxos'

    - name: Get list of VLAN interfaces
      set_fact:
          #vlan_interfaces: "{{ nxosfacts_out.ansible_facts.ansible_net_interfaces | regex_findall('Vlan') }}" 
          vlan_interfaces: "{{ nxosfacts_out.response }}" 
    - name: Debug
      debug:
        msg: "{{ vlan_interfaces }}"

    - name: Output data to file in YAML format
      copy: content="{{ nxosfacts_out | to_nice_yaml }}" dest="out/{{inventory_hostname}}_nxosfacts.yml"

