#- name: Configure Ethernet
#  eos_interface: name={{ item.name }} description="{{ item.description }}"
#    username={{ eapi_username }}
#    password={{ eapi_password }}
#    host={{ eapi_hostname }}
#    port={{ eapi_port }}
#    transport=https
#  with_items: interfaces

#- name: Configure Switchport
#  eos_switchport: name={{ item.name }} mode={{ item.mode }} access_vlan={{ item.vlanid }} trunk_native_vlan={{ item.native_vlan }} trunk_allowed_vlans="{{ item.allowed_vlans }}"
#    username={{ eapi_username }}
#    password={{ eapi_password }}
#    host={{ eapi_hostname }}
#    port={{ eapi_port }}
#    transport=https
#  with_items: interfaces

- name: Configure STP
  eos_stp_interface: name={{ item.name }} portfast={{ item.portfast }}
    username={{ eapi_username }}
    password={{ eapi_password }}
    host={{ eapi_hostname }}
    port={{ eapi_port }}
    transport=https
  with_items: interfaces
