---
- name: CONFIGURE 802.1X
  hosts: group1
  tasks:
    - name: DEFINE PROVIDER
      set_fact:
        netconf:
          host: "{{ ansible_ssh_host }}"
          username: "{{ ansible_ssh_user }}"
          password: "{{ ansible_ssh_pass }}"
          port: "{{ port }}"
          transport: netconf
          timeout: 30

    - name: Juniper connection test
      wait_for: host={{ inventory_hostname }} port={{ port }}

    - name: Get fpc numbers
      junos_command:
        commands:
          - "show chassis hardware"
        provider: "{{ netconf }}"
        display: xml
      register: result

    - name: output to file
      copy: content="{{ result.stdout[0] }}" dest=/tmp/fpc.txt

    - name: SET VARIABLE FPC
      set_fact:
        chassis_fpc="{{ lookup('xmlfile', 'file=/tmp/fpc.txt xpath=.//chassis[name="Chassis"]/chassis-module/name') | replace("\n","") }}"

    - name: Assign 802.1x port range 
      junos_config:
        lines:
          - set interfaces interface-range dot1x-ports member-range ge-{{ item[4:] }}/0/32 to ge-{{ item[4:] }}/0/47
        comment: Set 802.1x port ranges
        provider: "{{ netconf }}"
      with_items: "{{ chassis_fpc.split(',') }}"
      when: item | search("FPC")


    - name: Assign Vlans to 802.1x ports
      junos_config:
        lines:
          - set interfaces interface-range dot1x-ports unit 0 family ethernet-switching interface-mode access
          - set interfaces interface-range dot1x-ports unit 0 family ethernet-switching vlan members {{ item.name }}
        comment: Set Vlans
        provider: "{{ netconf }}"
      with_items: "{{ vlans }}"
      when: item.user == True

    - name: Set protocols
      junos_config:
        lines:
          - set protocols dot1x traceoptions file trace_dot
          - set protocols dot1x traceoptions flag dot1x-debug
          - set protocols dot1x traceoptions flag eapol
          - set protocols dot1x traceoptions flag vlan
          - set protocols dot1x traceoptions flag all
          - set protocols dot1x traceoptions flag parse
          - set protocols dot1x traceoptions flag config-internal
          - set protocols dot1x authenticator authentication-profile-name RAD-AUTH
          - set protocols dot1x authenticator interface dot1x-ports supplicant multiple
          - set protocols dot1x authenticator interface dot1x-ports mac-radius
          - set protocols dot1x authenticator interface dot1x-ports reauthentication 3600
          - set protocols dot1x authenticator interface dot1x-ports supplicant-timeout 30
          - set protocols dot1x authenticator interface dot1x-ports guest-vlan {{ guest_vlan }}
          - set protocols dot1x authenticator interface dot1x-ports server-reject-vlan {{ guest_vlan }}
          - set protocols dot1x authenticator interface dot1x-ports server-fail vlan-name {{ guest_vlan }}
        comment: Set 802.1x Protocols
        provider: "{{ netconf }}"




