---
- name: DEFINE SPANNING TREE
  hosts: group1
  tasks:
    - name: DEFINE PROVIDER
      set_fact:
        netconf:
          host: "{{ ansible_ssh_host }}"
          username: "{{ ansible_ssh_user }}"
          password: "{{ ansible_ssh_pass }}"
          port: "{{ port }}"
          transport: netconf
          timeout: 30

    - name: Juniper connection test
      wait_for: host={{ inventory_hostname }} port={{ port }}

    - name: DISABLE RSTP
      junos_config:
        lines:
          - delete protocols rstp
          - set protocols rstp disable
        comment: Globally Disable rstp
        provider: "{{ netconf }}"

    - name: ENABLE VSTP PER EACH VLAN
      junos_config:
        lines:
          - set protocols vstp vlan {{ item.vlanid }} bridge-priority 60k
          - set protocols vstp vlan {{ item.vlanid }} interface {{ item.port }} edge
          - set protocols vstp vlan {{ item.vlanid }} interface {{ item.port }} no-root-port
          - set protocols vstp vlan {{ item.vlanid }} interface ae0
          - set protocols vstp vlan {{ item.vlanid }} interface ae1
        comment: Set VSTP on all vlans with interfaces
        provider: "{{ netconf }}"
      with_items: "{{ vlans }}"
      when: item.port != 'NONE'

    - name: ENABLE VSTP For Guest VLAN
      junos_config:
        lines:
          - set protocols vstp vlan {{ guest_vlan }} bridge-priority 60k
          - set protocols vstp vlan {{ guest_vlan }} interface ae0
          - set protocols vstp vlan {{ guest_vlan }} interface ae1
        comment: Enable VSTP on Guest VLAN
        provider: "{{ netconf }}"
