---
- name: CONFIGURE SYSTEM SETTINGS
  hosts: group1
  tasks:
    - name: DEFINE PROVIDER
      set_fact:
        netconf:
          host: "{{ ansible_ssh_host }}"
          username: "{{ ansible_ssh_user }}"
          password: "{{ ansible_ssh_pass }}"
          port: "{{ port }}"
          transport: netconf
          timeout: 30
    - name: Juniper connection test
      wait_for: host={{ inventory_hostname }} port={{ port }}

    - name: Remove DHCP services
      junos_config:
        lines:
          - delete system processes dhcp-service
        comment: Removing DHCP-service process
        provider: "{{ netconf }}"

    - name: Change hostname/domain-name
      junos_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ domain_name }}"
        provider: "{{ netconf }}"

    - name: Set Authentication Order
      junos_config:
        lines:
          # Should be radius then password, but using temp IPs and not putting in radius makes it slower
          - set system authentication-order password
          - set system authentication-order radius
        comment: Update authentication order
        provider: "{{ netconf }}"

    - name: Change DNS
      junos_system:
        name_servers:
          - "{{ dns1 }}"
          - "{{ dns2 }}"
        provider: "{{ netconf }}"

    - name: Change NTP
      junos_config:
        lines:
          - set system ntp server {{ ntp1 }}
          - set system ntp server {{ ntp2 }}
          - set system ntp source-address {{ ansible_ssh_host }}
        comment: Update NTP settings
        provider: "{{ netconf }}"

    - name: Change User classes
      junos_config:
        lines:
          - set system login user RO class read-only
          - set system login user SU class super-user
          - set system login user remote class read-only
        comment: Update user settings
        provider: "{{ netconf }}"

    - name: SSH settings
      junos_config:
        lines:
          - set system services ssh root-login deny
          - set system services ssh protocol-version v2
          - set system services ssh client-alive-count-max 5
          - set system services ssh client-alive-interval 20
          - set system services ssh connection-limit 10
          - set system services ssh rate-limit 10
        comment: Update ssh settings
        provider: "{{ netconf }}"

    - name: Syslog settings
      junos_config:
        lines:
          - set system syslog user * any emergency
          - set system syslog host {{ syslog1 }} any info
          - set system syslog host {{ syslog2 }} any info
          - set system syslog file messages any notice
          - set system syslog file messages authorization info
          - deactivate system syslog file messages
          - set system syslog file interactive-commands interactive-commands any
          - set system syslog file User-Auth authorization any
          - set system syslog file User-Auth interactive-commands any
        comment: Update syslog settings
        provider: "{{ netconf }}"

    - name: Change Banner Message
      junos_banner:
        banner: login
        text: |
            +-------------------------------------------------------------+
            |               !!! Authorised access only !!!                |
            |     You are authorised to use this System for approved      |
            |     business purposes only. Use for any other purpose       |
            |     is prohibited.                                          |
            |                                                             |
            |     All transactional records generated by using this       |
            |       System are the property of RMS and may be             |
            |        used by RMS for any purpose. Authorised              |
            |     and unauthorised activities will be monitored.          |
            +-------------------------------------------------------------+

            +-------------------------------------------------------------+
            |     Disconnect IMMEDIATELY if you are not authorised        |
            |     For access to this system contact:                      |
            |                                                             |
            |              rms.networking@rms.com                         |
            +-------------------------------------------------------------+
        provider: "{{ netconf }}"
