---
- name: CONFIGURE JUNIPER EX
  hosts: nj_junos_ex
  tasks:
    - name: DEFINE PROVIDER
      set_fact:
        netconf:
          host: "{{ ansible_ssh_host }}"
          username: "{{ ansible_ssh_user }}"
          password: "{{ ansible_ssh_pass }}"
          port: "{{ port }}"
          transport: netconf
          timeout: 30
    - name: Juniper connection test
      wait_for: host={{ inventory_hostname }} port={{ port }}

    - name: Change hostname/domain-name
      junos_config:
        lines:
          - set system host-name nj-edge-sw01
          - set system domain-name rms.com
        comment: Update hostname settings
        provider: "{{ netconf }}"

    - name: Change DNS
      junos_config:
        lines:
          - set system name-server {{ dns1 }}
          - set system name-server {{ dns2 }} 
        comment: Update DNS settings
        provider: "{{ netconf }}"

    - name: Change NTP
      junos_config:
        lines:
          - set system ntp server {{ ntp1 }}
          - set system ntp server {{ ntp2 }}
        comment: Update NTP settings
        provider: "{{ netconf }}"

    - name: Change Radius
      junos_config:
        lines:
          - set system radius-server {{ radius1 }} secret {{ radius_key }}
          #- set system radius-server {{ radius1 }} source {{ ansible_ssh_host }}
          - set system radius-server {{ radius2 }} secret {{ radius_key }}
          #- set system radius-server {{ radius2 }} source {{ ansible_ssh_host }}
          - set system radius-server {{ radius3 }} secret {{ radius_key }}
          #- set system radius-server {{ radius3 }} source {{ ansible_ssh_host }}
        comment: Update Radius settings
        provider: "{{ netconf }}"

    - name: Change User classes
      junos_config:
        lines:
          - set system login user RO class read-only
          - set system login user SU class super-user
        comment: Update user settings
        provider: "{{ netconf }}"

    - name: SSH settings
      junos_config:
        lines:
          - set system services ssh root-login allow
          - set system services ssh protocol-version v2
        comment: Update ssh settings
        provider: "{{ netconf }}"

    - name: Syslog settings
      junos_config:
        lines:
          - set system syslog user * any emergency
          - set system syslog host {{ syslog1 }} any info
          - set system syslog host {{ syslog2 }} any info
          - set system syslog file messages any notice
          - set system syslog file messages authorization info
          - deactivate system syslog file messages
          - set system syslog file interactive-commands interactive-commands any
          - set system syslog file User-Auth authorization any
          - set system syslog file User-Auth interactive-commands any
        comment: Update syslog settings
        provider: "{{ netconf }}"

    - name: Change Banner Message
      junos_config:
        lines:
          - set system login message "\t\t\n+-------------------------------------------------------------+\t\t\n| !!! Authorized access only !!! |\t\t\n| You are authorized to use this System for approved |\t\t\n| business purposes only. Use for any other purpose |\t\t\n| is prohibited. |\t\t\n| |\t\t\n| All transactional records generated by using this |\t\t\n| System are the property of RMS and may be |\t\t\n| used by RMS for any purpose. Authorized |\t\t\n| and unauthorized activities will be monitored. |\t\t\n+-------------------------------------------------------------+\t\t\n+-------------------------------------------------------------+\t\t\n| Disconnect IMMEDIATELY if you are not authorized |\t\t\n| For access to this system contact{{ ":" }} |\t\t\n| |\t\t\n| rms.networking@rms.com |\t\t\n+-------------------------------------------------------------+\t\t\n"
        comment: Update Banner settings
        provider: "{{ netconf }}"
