---
- name: CONFIGURE UPLINKS
  hosts: test-sw01
  tasks:
    - name: DEFINE PROVIDER
      set_fact:
        netconf:
          host: "{{ ansible_ssh_host }}"
          username: "{{ ansible_ssh_user }}"
          password: "{{ ansible_ssh_pass }}"
          port: "{{ port }}"
          transport: netconf
          timeout: 30

    - name: Juniper connection test
      wait_for: host={{ inventory_hostname }} port={{ port }}

    - name: NETWORK INTERFACE TRUNK SETTINGS
      junos_config:
        lines:
          # FOR LOOP WITH VLANS to set member names
          - set interfaces ge-0/0/0 unit 0 family ethernet-switching interface-mode trunk
          - set interfaces ge-0/0/0 unit 0 family ethernet-switching vlan members all
        comment: Set Network Inferface Trunk settings
        provider: "{{ netconf }}"

    - name: NETWORK ROUTE SETTINGS
      junos_config:
        lines:

        comment: Set Network Route settings
        provider: "{{ netconf }}"
