---
- name: CONFIGURE VLANS
  hosts: category1
  tasks:
    - name: DEFINE PROVIDER
      set_fact:
        netconf:
          host: "{{ ansible_ssh_host }}"
          username: "{{ ansible_ssh_user }}"
          password: "{{ ansible_ssh_pass }}"
          port: "{{ port }}"
          transport: netconf
          timeout: 30

    - name: Juniper connection test
      wait_for: host={{ inventory_hostname }} port={{ port }}

    - name: Define Vlans
      junos_config:
        lines:
          - set vlans {{ item.name }} vlan-id {{ item.vlanid }}
        comment: Set Vlans
        provider: "{{ netconf }}"
      with_items: "{{ vlans }}"
    
    - name: Get fpc numbers
      junos_command:
        commands:
          - "show chassis hardware"
        provider: "{{ netconf }}"
        display: xml
      register: result

    - name: output to file
      copy: content="{{ result.stdout[0] }}" dest=/tmp/fpc_{{ inventory_hostname }}.txt

    - name: SET VARIABLE FPC
      set_fact:
        chassis_fpc="{{ lookup('xmlfile', 'file=/tmp/fpc_{{ inventory_hostname }}.txt xpath=.//chassis[name="Chassis"]/chassis-module/name') | replace("\n","") }}"

    - name: Assign User port range 
      junos_config:
        lines:
          - set interfaces interface-range USER-PORTS member-range ge-{{ item[4:] }}/0/4 to ge-{{ item[4:] }}/0/43
          - set interfaces interface-range WIFI-PORTS member-range ge-{{ item[4:] }}/0/44 to ge-{{ item[4:] }}/0/45
          - set interfaces interface-range VC-PORTS member-range ge-{{ item[4:] }}/0/46 to ge-{{ item[4:] }}/0/47
        comment: Set User Port ranges
        provider: "{{ netconf }}"
      with_items: "{{ chassis_fpc.split(',') }}"
      when: item | search("FPC")

    - name: Assign Vlans to Ports
      junos_config:
        lines:
          - set interfaces interface-range USER-PORTS unit 0 family ethernet-switching
          - set interfaces interface-range USER-PORTS unit 0 family ethernet-switching interface-mode access
          - set interfaces interface-range USER-PORTS unit 0 family ethernet-switching storm-control default
          - set interfaces interface-range USER-PORTS unit 0 family ethernet-switching vlan members {{ item.name }}
        comment: Set Vlans
        provider: "{{ netconf }}"
      with_items: "{{ vlans }}"
      when: item.user == True

    - name: Assign Wifi Vlans to Ports
      junos_config:
        lines:
          - set interfaces interface-range WIFI-PORTS native-vlan-id 12
          - set interfaces interface-range WIFI-PORTS unit 0 family ethernet-switching interface-mode trunk
          - set interfaces interface-range WIFI-PORTS unit 0 family ethernet-switching vlan members WIFI
          - set interfaces interface-range WIFI-PORTS unit 0 family ethernet-switching vlan members WIFI-GUEST
        comment: Set Vlans
        provider: "{{ netconf }}"

    - name: Assign Video-Conference Vlans to Ports
      junos_config:
        lines:
          - set interfaces interface-range VC-PORTS unit 0 family ethernet-switching interface-mode access
          - set interfaces interface-range VC-PORTS unit 0 family ethernet-switching vlan members VIDEO
        comment: Set Vlans
        provider: "{{ netconf }}"

    - name: Assign VOIP Ports
      junos_config:
        lines:
          - set switch-options voip interface access-ports vlan {{ voice_vlan }}
          - set switch-options voip interface USER-PORTS vlan {{ voice_vlan }}
        comment: Set Voip vlans on user/access ports
        provider: "{{ netconf }}"
 
    - name: Delete IRB DHCP 
      junos_config:
        lines:
          - delete interfaces irb unit 0 family inet dhcp
        comment: Delete IRB interface DHCP
        provider: "{{ netconf }}"
 
